keyword_data = {
    "Smart Baby Monitor": ["IoT Baby Monitor", "Baby Monitor"],
    "Smart Speakers": ["Amazon Echo", "Google Home", "Apple HomePod", "Smart Speaker"],
    "Smart Thermostats": ["Nest Thermostat", "Ecobee SmartThermostat", "Honeywell Home T9", "Smart Themostat"],
    "Smart Locks": ["August Smart Lock", "Schlage Encode", "Yale Assure Lock", "Smart Lock"],
    "Smart Lights": ["Philips Hue", "LIFX", "TP-Link Kasa", "Smart Light", "Smart Bulb"],
    "Smart Cameras": ["Ring Video Doorbell", "Arlo Pro", "Wyze Cam", "Camera"],
    "Smart Plugs": ["TP-Link Kasa Smart Plug", "Belkin WeMo Mini", "Smart Plug"],
    "Smart Fridge": ["Refrigerator", "Smart Fridge"],
    "Smart Washer": ["Smart Washing Machine", "Smart Washer"],
    "Smart TVs": ["Smart Televisions", "Smart TV"],
    "Home Security": ["Ring Alarm", "SimpliSafe", "ADT Pulse", "Alarm", "Smart Camera"],
    "Smart Door Locks": ["Yale Assure Lever", "Schlage Connect", "Kwikset Halo",  "Smart Door Lock"],
    "Smart Blinds, Shades": ["Serena, Lutron", "Axis Gear", "Bali Blind", "Smart Blind"],
    "Smart Smoke Detectors": ["Nest Protect", "First Alert Onelink", "Kidde RemoteLync", "Smart Smoke Detector"],
    "Smart Sprinkler Systems": ["Rachio 3", "Orbit B-hyve", "RainMachine, “Smart Sprinkler”],
    "Smart Health Devices": ["Fitbit", "Apple Watch", "Withings Body+ Scale", "Smart Scale", "Fitness Tracker", "Smart Watch"],
    "Smart Vacuum Cleaners": ["iRobot Roomba", "Eufy RoboVac", "Shark IQ Robot", "Smart Vacuum", "Vacuum Robot"],
    "Smart Kitchen Appliances": ["Instant Pot Smart WiFi", "Behmor Connected Coffee Maker", "Anova Precision Cooker", "Smart Kitchen"],
    "Smart Mirrors": ["HiMirror", "Simplehuman Sensor Mirror", "CareOS”, “Smart Mirror"],
    "Smart Pet Feeders": ["Petnet SmartFeeder", "WOPET Automatic Feeder", "PetSafe Smart Feed", "Pet Feeder", "Smart Feeder"],
    "Smart Garden Sensors": ["Parrot Flower Power", "Xiaomi MiFlora", "OSOYOO Soil Moisture Sensor"],
    "Smart Water Monitors": ["Phyn Plus", "Flume Smart Water Monitor", "StreamLabs Control"],
    "Smart Garage Door Openers": ["Chamberlain MyQ", "Nexx Garage", "Tailwind iQ3", "Garage"],
    "Home Assistants": ["Jarvis", "OpenHAB", "Home Assistant", "Google Home"]
}
