keyword_data = {
"Smart Fridge": [
    "Refrigerator", 
    "Fridge", 
    "Smart Refrigerator", 
    "Connected Fridge", 
    "Refrigeration Appliance",
    "Samsung Family Hub", 
    "LG InstaView", 
    "Whirlpool Smart French Door", 
    "GE Profile Series"
],
"Smart Washer": [
    "Washing Machine", 
    "Washer", 
    "Smart Washing Machine", 
    "Connected Washer", 
    "Laundry Appliance",
    "Samsung FlexWash", 
    "LG TwinWash", 
    "Whirlpool Smart Front Load", 
    "GE Smart Top Load"
],
"Smart TVs": [
    "Televisions", 
    "TV", 
    "TVs", 
    "Smart Television", 
    "Connected TV", 
    "Smart Display",
    "Samsung QLED", 
    "LG OLED", 
    "Sony Bravia", 
    "Vizio SmartCast"
],
"Smart Thermostats": [
    "Thermostats", 
    "Climate Control", 
    "Smart Climate Control", 
    "Connected Thermostat", 
    "Temperature Regulator",
    "Nest Learning Thermostat", 
    "Ecobee SmartThermostat", 
    "Honeywell Lyric T6", 
    "Emerson Sensi"
],
"Smart Locks": [
    "Door Locks", 
    "Smart Door Locks", 
    "Smart Locking System", 
    "Connected Locks", 
    "Electronic Deadbolt",
    "August Smart Lock", 
    "Schlage Encode", 
    "Yale Assure Lock", 
    "Kwikset SmartCode"
],
"Smart Speakers": [
    "Smart Speaker", 
    "Voice Assistant", 
    "AI Assistant", 
    "Intelligent Speaker", 
    "Voice-Activated Speaker", 
    "Connected Speaker",
    "Amazon Echo", 
    "Google Home", 
    "Apple HomePod", 
    "Sonos One"
],
"Smart Plugs": [
    "Smart Outlets", 
    "Plug Adapters", 
    "Smart Socket", 
    "Connected Plug", 
    "Wireless Outlet",
    "TP-Link Kasa Smart Plug", 
    "Belkin Wemo Mini", 
    "Amazon Smart Plug", 
    "Google Nest Mini"
],
"Smart Lights": [
    "Smart Bulbs", 
    "Smart Lighting", 
    "Connected Lights", 
    "Wireless Light Fixtures", 
    "Intelligent Illumination",
    "Philips Hue", 
    "LIFX", 
    "Wyze Bulb", 
    "Sengled Element"
],
"Smart Cameras": [
    "Security Cameras", 
    "Surveillance Cameras", 
    "Smart Security Cameras", 
    "Connected Surveillance", 
    "CCTV",
    "Arlo Pro", 
    "Ring Stick Up Cam", 
    "Google Nest Cam", 
    "Blink XT2"
],
"Smart Doorbells": [
    "Video Doorbells", 
    "Doorbell Cameras", 
    "Smart Video Doorbells", 
    "Connected Doorbell", 
    "Wireless Door Camera",
    "Ring Video Doorbell", 
    "Nest Hello", 
    "August Doorbell Cam", 
    "Eufy Video Doorbell"
],
"Smart Baby Monitors": [
    "Baby Monitors", 
    "Baby Cameras", 
    "Infant Surveillance", 
    "Connected Baby Monitor", 
    "Nursery Monitor",
    "Nanit Pro", 
    "iBaby Monitor M7", 
    "Arlo Baby", 
    "Motorola Halo"
],
"Smart Smoke Detectors": [
    "Smoke Alarms", 
    "Fire Detectors", 
    "Smart Fire Alarms", 
    "Connected Smoke Detector", 
    "Fire Safety System",
    "Nest Protect", 
    "First Alert Onelink", 
    "Roost Smart Battery", 
    "Kidde RemoteLync"
],
"Smart Air Purifiers": [
    "Air Purifiers", 
    "Air Cleaners", 
    "Smart Air Cleaners", 
    "Connected Air Purification", 
    "Indoor Air Quality Monitor",
    "Dyson Pure Cool", 
    "Coway Airmega", 
    "Levoit LV-H132", 
    "Honeywell HPA300"
],
"Smart Vacuum Cleaners": [
    "Robotic Vacuums", 
    "Robot Vacuum Cleaners", 
    "Smart Robotic Cleaners", 
    "Connected Vacuum", 
    "Automated Cleaning",
    "iRobot Roomba", 
    "Ecovacs Deebot", 
    "Shark IQ Robot", 
    "Neato Botvac"
],
"Smart Coffee Makers": [
    "Coffee Machines", 
    "Smart Coffee Machines", 
    "Connected Coffee Maker", 
    "Automatic Brewer", 
    "Espresso Machine",
    "Nespresso Vertuo", 
    "Keurig K-Elite", 
    "Breville Barista", 
    "De'Longhi Magnifica"
],
"Smart Ovens": [
    "Smart Toaster Ovens", 
    "Smart Wall Ovens", 
    "Connected Oven", 
    "Intelligent Cooking Appliance", 
    "Digital Baking Oven",
    "June Oven", 
    "Breville Smart Oven", 
    "Samsung Wall Oven", 
    "GE Profile Wall Oven"
],
"Smart Microwaves": [
    "Smart Microwave Ovens", 
    "Microwaves", 
    "Connected Microwave", 
    "Intelligent Microwave", 
    "Digital Oven",
    "AmazonBasics Microwave", 
    "Whirlpool Smart Over-the-Range Microwave", 
    "Sharp SMC1585BS", 
    "Panasonic NN-SD975S"
],
"Smart Dishwashers": [
    "Smart Dish Cleaning", 
    "Dishwashers", 
    "Connected Dishwasher", 
    "Automatic Dish Cleaning", 
    "Intelligent Dishwasher",
    "Bosch 800 Series", 
    "Samsung DW80R9950US", 
    "GE Profile PDT715SYNFS", 
    "LG LDT7808BD"
],
"Smart Door Locks": [
    "Smart Locks", 
    "Digital Door Locks", 
    "Connected Door Locks", 
    "Intelligent Locking System", 
    "Wireless Deadbolt",
    "August Smart Lock Pro", 
    "Schlage Encode", 
    "Yale Assure Lock", 
    "Kwikset SmartCode"
],
"Smart Window Blinds": [
    "Smart Blinds", 
    "Automated Window Coverings", 
    "Connected Window Shades", 
    "Motorized Blinds", 
    "Intelligent Drapes",
    "Lutron Serena", 
    "Somfy Motorized Shades", 
    "IKEA Fyrtur", 
    "Soma Smart Shades 2"
],
"Smart Refrigerators": [
    "Refrigerators", 
    "Fridges", 
    "Smart Refrigerators", 
    "Connected Fridges", 
    "Refrigeration Appliances",
    "Samsung Family Hub", 
    "LG InstaView", 
    "Whirlpool Smart French Door", 
    "GE Profile Series"
],
"Smart Ceiling Fans": [
    "Smart Fans", 
    "Ceiling Fans", 
    "Connected Ceiling Fan", 
    "Intelligent Air Circulator", 
    "Automated Ventilation",
    "Hunter Symphony", 
    "Haiku L Series", 
    "Casablanca Stealth", 
    "Big Ass Fans Haiku"
],
"Smart Power Strips": [
    "Smart Surge Protectors", 
    "Power Strips", 
    "Connected Power Strip", 
    "Intelligent Power Hub", 
    "Wireless Outlet Strip",
    "Kasa Smart Power Strip", 
    "TP-Link Kasa Smart Strip", 
    "Belkin Wemo", 
    "Eve Energy Strip"
],
"Smart Humidifiers": [
    "Humidifiers", 
    "Smart Air Humidifiers", 
    "Connected Humidifier", 
    "Intelligent Moisture Control", 
    "Air Moisturizer",
    "Dyson AM10", 
    "Honeywell HE360A", 
    "Levoit LV600HH", 
    "Elechomes SH8820"
],
"Smart Sprinkler Systems": [
    "Irrigation Systems", 
    "Lawn Sprinklers", 
    "Connected Sprinkler", 
    "Intelligent Irrigation", 
    "Automated Watering System",
    "Rachio 3", 
    "Orbit B-Hyve", 
    "RainMachine Touch HD", 
    "NxEco Smart Sprinkler"
],
"Smart Alarm Clocks": [
    "Smart Clocks", 
    "Alarm Clocks", 
    "Connected Alarm Clock", 
    "Intelligent Wake-Up System", 
    "Digital Timepiece",
    "Lenovo Smart Clock", 
    "iHome iBT29", 
    "Amazon Echo Show 5", 
    "Google Nest Hub"
],
"Smart Mirrors": [
    "Smart Vanity Mirrors", 
    "Connected Mirrors", 
    "Intelligent Reflecting Surface", 
    "Digital Makeup Mirror", 
    "Interactive Mirror",
    "HiMirror Mini", 
    "simplehuman Sensor Mirror", 
    "Capstone Connected Thin Mirror", 
    "iHome Reflect Pro"
],
"Smart Pet Feeders": [
    "Automatic Pet Feeders", 
    "Pet Food Dispensers", 
    "Connected Pet Feeder", 
    "Intelligent Pet Feeding System", 
    "Digital Animal Feeder",
    "PetSafe Smart Feed", 
    "WOPET Automatic Pet Feeder", 
    "Arf Pets Automatic Pet Feeder", 
    "Feed and Go Smart Pet Feeder"
],
"Smart Blenders": [
    "Blender Appliances", 
    "High-Speed Blenders", 
    "Connected Blender", 
    "Intelligent Mixing Appliance", 
    "Digital Smoothie Maker",
    "Vitamix Ascent Series", 
    "Blendtec Designer 725", 
    "Ninja Professional BL610", 
    "NutriBullet Pro 900 Series"
],
"Smart Sous Vide Precision Cookers": [
    "Sous Vide Cookers", 
    "Immersion Circulators", 
    "Connected Sous Vide", 
    "Intelligent Cooking Device", 
    "Digital Water Oven",
    "Anova Culinary Nano", 
    "Joule Sous Vide", 
    "Instant Pot Accu Slim", 
    "Monoprice Strata Home Sous Vide"
],
"Smart Air Conditioners": [
    "Air Conditioning Units", 
    "AC Systems", 
    "Connected Air Conditioner", 
    "Intelligent Cooling System", 
    "Digital Climate Control",
    "LG Dual Inverter", 
    "Midea U Inverter", 
    "Frigidaire Cool Connect", 
    "GE Smart Window AC"
],
"Smart Water Heaters": [
    "Hot Water Heaters", 
    "Tankless Water Heaters", 
    "Connected Water Heater", 
    "Intelligent Heating Appliance", 
    "Digital Hot Water System",
    "Rheem Performance Platinum", 
    "EcoSmart ECO 27", 
    "Stiebel Eltron Tempra Plus", 
    "Bosch Tronic 3000"
],
"Smart Kettles": [
    "Electric Kettles", 
    "Smart Tea Kettles", 
    "Connected Kettle", 
    "Intelligent Water Boiler", 
    "Digital Tea Maker",
    "Fellow Stagg EKG", 
    "COSORI Electric Kettle", 
    "OXO Brew Adjustable Temperature Kettle", 
    "Bonavita BV382510V"
],
"Smart Weight Scales": [
    "Digital Bathroom Scales", 
    "Body Weight Monitors", 
    "Connected Weight Scale", 
    "Intelligent Body Analyzer", 
    "Digital Health Scale",
    "Withings Body+", 
    "Fitbit Aria 2", 
    "Eufy Smart Scale", 
    "Yunmai Premium Smart Scale"
]

}
